---
- name: Prompt for user input
  hosts: all
  vars_prompt: 
    - name: user_name
      prompt: Please enter your username
      private: no
    - name: password
      prompt: Please enter your password
      private: yes
  tasks: 
    - debug: 
        msg: "The username is {{ user_name }} and password is {{ password }}"
...
